// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Designaciones.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Designaciones.Infrastructure.Migrations
{
    [DbContext(typeof(DesignacionesDbContext))]
    partial class DesignacionesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("designaciones")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Designaciones.Domain.Cargo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("abreviatura");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("cargos", "designaciones", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.ComandoIdempotente", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("Clave")
                        .HasColumnType("uuid")
                        .HasColumnName("clave");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_body");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ruta");

                    b.Property<int>("StatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("status_code");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "Ruta", "Clave")
                        .IsUnique();

                    b.ToTable("idempotencia_comandos", "designaciones", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.Dedicacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<short>("Codigo")
                        .HasColumnType("smallint")
                        .HasColumnName("codigo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<short>("Orden")
                        .HasColumnType("smallint")
                        .HasColumnName("orden");

                    b.HasKey("Id");

                    b.HasIndex("Codigo")
                        .IsUnique();

                    b.ToTable("dedicaciones", "designaciones", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.Designacion", b =>
                {
                    b.Property<int?>("HorasInvestigacion")
                        .HasColumnType("integer")
                        .HasColumnName("horas_investigacion");

                    b.Property<int?>("HorasExternas")
                        .HasColumnType("integer")
                        .HasColumnName("horas_externas");

                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CargoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Dedicacion")
                        .HasColumnType("text")
                        .HasColumnName("dedicacion");

                    b.Property<Guid?>("DedicacionId")
                        .HasColumnType("uuid")
                        .HasColumnName("dedicacion_id");

                    b.Property<int>("Horas")
                        .HasColumnType("integer")
                        .HasColumnName("horas");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("materia_id");

                    b.Property<Guid?>("OrigenPedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("origen_pedido_id");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date")
                        .HasColumnName("vigente_desde");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date")
                        .HasColumnName("vigente_hasta");

                    b.HasKey("Id");

                    b.HasIndex("CargoId");

                    b.HasIndex("DedicacionId");

                    b.ToTable("designaciones", "designaciones", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CargoSolicitadoId")
                        .HasColumnType("uuid")
                        .HasColumnName("cargo_solicitado_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedicacionSolicitada")
                        .HasColumnType("text")
                        .HasColumnName("dedicacion_solicitada");

                    b.Property<Guid?>("DedicacionSolicitadaId")
                        .HasColumnType("uuid")
                        .HasColumnName("dedicacion_solicitada_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<string>("EtapaRetorno")
                        .HasColumnType("text")
                        .HasColumnName("etapa_retorno");

                    b.Property<int?>("Horas")
                        .HasColumnType("integer")
                        .HasColumnName("horas");

                    b.Property<int?>("HorasExternas")
                        .HasColumnType("integer")
                        .HasColumnName("horas_externas");

                    b.Property<int?>("HorasInvestigacion")
                        .HasColumnType("integer")
                        .HasColumnName("horas_investigacion");

                    b.Property<string>("Justificacion")
                        .HasColumnType("text")
                        .HasColumnName("justificacion");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("materia_id");

                    b.Property<string>("Novedad")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("novedad");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("numero");

                    b.Property<Guid>("PeriodoId")
                        .HasColumnType("uuid")
                        .HasColumnName("periodo_id");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.Property<bool>("Prioritario")
                        .HasColumnType("boolean")
                        .HasColumnName("prioritario");

                    b.Property<string>("PropietarioActual")
                        .HasColumnType("text")
                        .HasColumnName("propietario_actual");

                    b.Property<string>("Snapshot")
                        .HasColumnType("jsonb")
                        .HasColumnName("snapshot");

                    b.Property<string>("TipoBaja")
                        .HasColumnType("text")
                        .HasColumnName("tipo_baja");

                    b.Property<string>("TipoBajaDetalle")
                        .HasColumnType("text")
                        .HasColumnName("tipo_baja_detalle");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.HasIndex("CargoSolicitadoId");

                    b.HasIndex("DedicacionSolicitadaId");

                    b.HasIndex("Numero")
                        .IsUnique();

                    b.HasIndex("PeriodoId");

                    b.ToTable("pedidos", "designaciones", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.PedidoAdjunto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("pedido_adjuntos", "designaciones", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.PedidoHistorial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Accion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("accion");

                    b.Property<Guid?>("ActorId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_id");

                    b.Property<string>("Comentario")
                        .HasColumnType("text")
                        .HasColumnName("comentario");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Etapa")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etapa");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<Guid>("RolId")
                        .HasColumnType("uuid")
                        .HasColumnName("rol_id");

                    b.HasKey("Id");

                    b.HasIndex("PedidoId");

                    b.ToTable("pedido_historial", "designaciones", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.Periodo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean")
                        .HasColumnName("activo");

                    b.Property<DateOnly>("CargaDesde")
                        .HasColumnType("date")
                        .HasColumnName("carga_desde");

                    b.Property<DateOnly>("CargaHasta")
                        .HasColumnType("date")
                        .HasColumnName("carga_hasta");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("ImpactoDesde")
                        .HasColumnType("date")
                        .HasColumnName("impacto_desde");

                    b.Property<DateOnly>("ImpactoHasta")
                        .HasColumnType("date")
                        .HasColumnName("impacto_hasta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id");

                    b.ToTable("periodos", "designaciones", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.Designacion", b =>
                {
                    b.HasOne("Modules.Designaciones.Domain.Cargo", "Cargo")
                        .WithMany()
                        .HasForeignKey("CargoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Designaciones.Domain.Dedicacion", "DedicacionCatalogo")
                        .WithMany()
                        .HasForeignKey("DedicacionId");

                    b.Navigation("Cargo");

                    b.Navigation("DedicacionCatalogo");
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.Pedido", b =>
                {
                    b.HasOne("Modules.Designaciones.Domain.Cargo", "CargoSolicitado")
                        .WithMany()
                        .HasForeignKey("CargoSolicitadoId");

                    b.HasOne("Modules.Designaciones.Domain.Dedicacion", "DedicacionSolicitadaCatalogo")
                        .WithMany()
                        .HasForeignKey("DedicacionSolicitadaId");

                    b.HasOne("Modules.Designaciones.Domain.Periodo", "Periodo")
                        .WithMany()
                        .HasForeignKey("PeriodoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CargoSolicitado");

                    b.Navigation("DedicacionSolicitadaCatalogo");

                    b.Navigation("Periodo");
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.PedidoAdjunto", b =>
                {
                    b.HasOne("Modules.Designaciones.Domain.Pedido", "Pedido")
                        .WithMany("Adjuntos")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.PedidoHistorial", b =>
                {
                    b.HasOne("Modules.Designaciones.Domain.Pedido", "Pedido")
                        .WithMany("Historial")
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pedido");
                });

            modelBuilder.Entity("Modules.Designaciones.Domain.Pedido", b =>
                {
                    b.Navigation("Adjuntos");

                    b.Navigation("Historial");
                });
#pragma warning restore 612, 618
        }
    }
}
