// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Portal.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Portal.Infrastructure.Migrations
{
    [DbContext(typeof(PortalDbContext))]
    partial class PortalDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("portal")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Portal.Domain.Certificacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Emisor")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("emisor");

                    b.Property<DateOnly>("Fecha")
                        .HasColumnType("date")
                        .HasColumnName("fecha");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<DateOnly?>("Vencimiento")
                        .HasColumnType("date")
                        .HasColumnName("vencimiento");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("certificaciones", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.Contacto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Mail")
                        .HasColumnType("text")
                        .HasColumnName("mail");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Telefono")
                        .HasColumnType("text")
                        .HasColumnName("telefono");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId")
                        .IsUnique();

                    b.ToTable("contactos", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.Cv", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArchivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("archivo_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FechaCarga")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId")
                        .IsUnique();

                    b.ToTable("cvs", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.DocenteHabilidad", b =>
                {
                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<Guid>("HabilidadId")
                        .HasColumnType("uuid")
                        .HasColumnName("habilidad_id");

                    b.Property<string>("Tipo")
                        .HasColumnType("text")
                        .HasColumnName("tipo");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("PerfilId", "HabilidadId", "Tipo");

                    b.HasIndex("HabilidadId");

                    b.ToTable("docente_habilidades", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.DocumentoProyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArchivoId")
                        .HasColumnType("uuid")
                        .HasColumnName("archivo_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("FechaCarga")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_carga");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("ProyectoId")
                        .HasColumnType("uuid")
                        .HasColumnName("proyecto_id");

                    b.Property<string>("Uri")
                        .HasColumnType("text")
                        .HasColumnName("uri");

                    b.HasKey("Id");

                    b.HasIndex("ProyectoId")
                        .IsUnique();

                    b.ToTable("proyecto_documentos", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.Educacion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Carrera")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("carrera");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("Institucion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("institucion");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("educaciones", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.Experiencia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("Organizacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("organizacion");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Puesto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("puesto");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("experiencias", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.Habilidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CanonicaId")
                        .HasColumnType("uuid")
                        .HasColumnName("canonica_id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("Sugerido")
                        .HasColumnType("boolean")
                        .HasColumnName("sugerido");

                    b.Property<string>("Termino")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("termino");

                    b.Property<string>("TerminoNorm")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("termino_norm");

                    b.Property<int>("Usos")
                        .HasColumnType("integer")
                        .HasColumnName("usos");

                    b.HasKey("Id");

                    b.HasIndex("TerminoNorm")
                        .IsUnique();

                    b.ToTable("habilidades", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.Perfil", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PersonaId")
                        .HasColumnType("uuid")
                        .HasColumnName("persona_id");

                    b.HasKey("Id");

                    b.HasIndex("PersonaId")
                        .IsUnique();

                    b.ToTable("perfiles", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.Proyecto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("descripcion");

                    b.Property<DateOnly>("Desde")
                        .HasColumnType("date")
                        .HasColumnName("desde");

                    b.Property<string>("Doi")
                        .HasColumnType("text")
                        .HasColumnName("doi");

                    b.Property<DateOnly?>("Hasta")
                        .HasColumnType("date")
                        .HasColumnName("hasta");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<Guid>("PerfilId")
                        .HasColumnType("uuid")
                        .HasColumnName("perfil_id");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rol");

                    b.HasKey("Id");

                    b.HasIndex("PerfilId");

                    b.ToTable("proyectos", "portal", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Modules.Portal.Domain.Certificacion", b =>
                {
                    b.HasOne("Modules.Portal.Domain.Perfil", null)
                        .WithMany("Certificaciones")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Portal.Domain.Contacto", b =>
                {
                    b.HasOne("Modules.Portal.Domain.Perfil", null)
                        .WithOne("Contacto")
                        .HasForeignKey("Modules.Portal.Domain.Contacto", "PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Portal.Domain.Cv", b =>
                {
                    b.HasOne("Modules.Portal.Domain.Perfil", null)
                        .WithOne("Cv")
                        .HasForeignKey("Modules.Portal.Domain.Cv", "PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Portal.Domain.DocenteHabilidad", b =>
                {
                    b.HasOne("Modules.Portal.Domain.Habilidad", "Habilidad")
                        .WithMany()
                        .HasForeignKey("HabilidadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Modules.Portal.Domain.Perfil", null)
                        .WithMany("Habilidades")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Habilidad");
                });

            modelBuilder.Entity("Modules.Portal.Domain.DocumentoProyecto", b =>
                {
                    b.HasOne("Modules.Portal.Domain.Proyecto", null)
                        .WithOne("Documento")
                        .HasForeignKey("Modules.Portal.Domain.DocumentoProyecto", "ProyectoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Portal.Domain.Educacion", b =>
                {
                    b.HasOne("Modules.Portal.Domain.Perfil", null)
                        .WithMany("Educaciones")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Portal.Domain.Experiencia", b =>
                {
                    b.HasOne("Modules.Portal.Domain.Perfil", null)
                        .WithMany("Experiencias")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Portal.Domain.Proyecto", b =>
                {
                    b.HasOne("Modules.Portal.Domain.Perfil", null)
                        .WithMany("Proyectos")
                        .HasForeignKey("PerfilId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Modules.Portal.Domain.Perfil", b =>
                {
                    b.Navigation("Certificaciones");

                    b.Navigation("Contacto");

                    b.Navigation("Cv");

                    b.Navigation("Educaciones");

                    b.Navigation("Experiencias");

                    b.Navigation("Habilidades");

                    b.Navigation("Proyectos");
                });

            modelBuilder.Entity("Modules.Portal.Domain.Proyecto", b =>
                {
                    b.Navigation("Documento");
                });
#pragma warning restore 612, 618
        }
    }
}
