// <auto-generated />
using System;
using ArsDocendi.Storage.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ArsDocendi.Storage.Infrastructure.Migrations
{
    [DbContext(typeof(AlmacenamientoDbContext))]
    partial class AlmacenamientoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("storage")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ArsDocendi.Storage.Infrastructure.ArchivoEntidad", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Ambiente")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ambiente");

                    b.Property<string>("Bucket")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bucket");

                    b.Property<string>("ClaveObjeto")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("clave_objeto");

                    b.Property<DateTimeOffset?>("ConfirmadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("confirmado_at");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("EliminadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("eliminado_at");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<DateTimeOffset>("ExpiraEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_en");

                    b.Property<string>("MimeDeclarado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mime_declarado");

                    b.Property<string>("MimeDetectado")
                        .HasColumnType("text")
                        .HasColumnName("mime_detectado");

                    b.Property<string>("MotivoRevision")
                        .HasColumnType("text")
                        .HasColumnName("motivo_revision");

                    b.Property<string>("NombreOriginal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre_original");

                    b.Property<Guid>("PropietarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("propietario_id");

                    b.Property<string>("Proposito")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proposito");

                    b.Property<DateTimeOffset?>("RevisadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revisado_at");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<long>("TamanoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("tamano_bytes");

                    b.HasKey("Id");

                    b.HasIndex("Ambiente", "ClaveObjeto")
                        .IsUnique();

                    b.HasIndex("Estado", "ExpiraEn");

                    b.HasIndex("PropietarioId", "Estado");

                    b.ToTable("archivos", "storage", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
