// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ArsDocendi.Storage.Infrastructure;

namespace ArsDocendi.Storage.Infrastructure.Migrations;

[DbContext(typeof(AlmacenamientoDbContext))]
public sealed class AlmacenamientoDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
        modelBuilder.HasDefaultSchema("storage").HasAnnotation("ProductVersion", "10.0.11");
        modelBuilder.Entity<ArchivoEntidad>(e =>
        {
            e.ToTable("archivos", "storage", t => t.ExcludeFromMigrations());
            e.HasKey(x => x.Id);
            e.Property(x => x.Id).HasColumnName("id");
            e.Property(x => x.Proposito).HasColumnName("proposito");
            e.Property(x => x.Ambiente).HasColumnName("ambiente");
            e.Property(x => x.Bucket).HasColumnName("bucket");
            e.Property(x => x.ClaveObjeto).HasColumnName("clave_objeto");
            e.Property(x => x.NombreOriginal).HasColumnName("nombre_original");
            e.Property(x => x.MimeDeclarado).HasColumnName("mime_declarado");
            e.Property(x => x.MimeDetectado).HasColumnName("mime_detectado");
            e.Property(x => x.TamanoBytes).HasColumnName("tamano_bytes");
            e.Property(x => x.Sha256).HasColumnName("sha256");
            e.Property(x => x.Estado).HasColumnName("estado");
            e.Property(x => x.PropietarioId).HasColumnName("propietario_id");
            e.Property(x => x.ExpiraEn).HasColumnName("expira_en");
            e.Property(x => x.CreadoEn).HasColumnName("created_at");
            e.Property(x => x.ConfirmadoEn).HasColumnName("confirmado_at");
            e.Property(x => x.RevisadoEn).HasColumnName("revisado_at");
            e.Property(x => x.MotivoRevision).HasColumnName("motivo_revision");
            e.Property(x => x.EliminadoEn).HasColumnName("eliminado_at");
            e.HasIndex(x => new { x.Estado, x.ExpiraEn });
            e.HasIndex(x => new { x.PropietarioId, x.Estado });
            e.HasIndex(x => new { x.Ambiente, x.ClaveObjeto }).IsUnique();
        });
    }
}
