// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Aulas.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Aulas.Infrastructure.Migrations
{
    [DbContext(typeof(AulasDbContext))]
    [Migration("20260920010000_SchemaAulasSolicitudes")]
    partial class SchemaAulasSolicitudes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("aulas")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Aulas.Domain.SolicitudReservaAula", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AulaAsignada")
                        .HasColumnType("text")
                        .HasColumnName("aula_asignada");

                    b.Property<int>("CantidadAlumnosAprox")
                        .HasColumnType("integer")
                        .HasColumnName("cantidad_alumnos_aprox");

                    b.Property<string>("Comision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comision");

                    b.Property<DateTimeOffset>("CreadoEn")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateOnly>("Dia")
                        .HasColumnType("date")
                        .HasColumnName("dia");

                    b.Property<Guid>("DocenteId")
                        .HasColumnType("uuid")
                        .HasColumnName("docente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estado");

                    b.Property<TimeOnly>("HorarioDesde")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_desde");

                    b.Property<TimeOnly>("HorarioHasta")
                        .HasColumnType("time without time zone")
                        .HasColumnName("horario_hasta");

                    b.Property<Guid>("MateriaId")
                        .HasColumnType("uuid")
                        .HasColumnName("materia_id");

                    b.Property<string>("MotivoRechazo")
                        .HasColumnType("text")
                        .HasColumnName("motivo_rechazo");

                    b.HasKey("Id");

                    b.HasIndex("DocenteId");

                    b.HasIndex("Estado");

                    b.HasIndex("MateriaId");

                    b.ToTable("solicitudes_reserva", "aulas", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
